### ISSUE TITLE
Signature check while installing some apps (PRG) on Venu 2 Plus

### ISSUE THREAD

**Issue by daitj** [abadiet/GarminServerLess#3]
Out of 5 apps I installed, three of them threw this error, Flappy Bird Fork and SubMusic were installed but for three I get this
```
---
Error: 'Signature check failed on file: Data_Lover'
Time: 2024-10-03T11:12:57Z
Part-Number: 006-B3851-00
Firmware-Version: '15.20'
Language-Code: eng
---
Error: 'Signature check failed on file: Falcon_X'
Time: 2024-10-03T11:39:22Z
Part-Number: 006-B3851-00
Firmware-Version: '15.20'
Language-Code: eng
---
Error: 'Signature check failed on file: Avak'
Time: 2024-10-03T11:39:22Z
Part-Number: 006-B3851-00
Firmware-Version: '15.20'
Language-Code: eng
```

**Comment by daitj** [comment]
I just bought the watch, I use Gadgetbrigde  in Android. I was just looking into possiblity of using the device completely offline.

**Comment by abadiet** [comment]
> Out of 5 apps I installed, three of them threw this error, Flappy Bird Fork and SubMusic were installed but for three I get this
> 
> ```
> ---
> Error: 'Signature check failed on file: Data_Lover'
> Time: 2024-10-03T11:12:57Z
> Part-Number: 006-B3851-00
> Firmware-Version: '15.20'
> Language-Code: eng
> ---
> Error: 'Signature check failed on file: Falcon_X'
> Time: 2024-10-03T11:39:22Z
> Part-Number: 006-B3851-00
> Firmware-Version: '15.20'
> Language-Code: eng
> ---
> Error: 'Signature check failed on file: Avak'
> Time: 2024-10-03T11:39:22Z
> Part-Number: 006-B3851-00
> Firmware-Version: '15.20'
> Language-Code: eng
> ```

That's interesting. Actually, thanks to reverse engineering GE, I knew that Garmin was signing with RSA some of its apps but I never found one signed in the CIQ store. I'll take a look at these apps


> I just bought the watch, I use Gadgetbrigde in Android. I was just looking into possiblity of using the device completely offline.

I never used Gadgetbrigde, but I think it is the best option so far. GSL is still at a very early stages of development and unfortunately I don't have that much time to continue to develop it...

**Comment by daitj** [comment]
No worries, we all do it when we have time. That is how OSS works. 

You have put out what you have done so far, this is already a lot. With this and your extension (which I converted it into a Violentmonkey userscript for easy editing) to download PRG. I saved bunch of time figuring out how to do that myself.  

I am trying to update the watch to latest version to see if signature issue are because some newer certificates are missing from the watch.

**Comment by abadiet** [comment]
This issue is likely linked to [this comment](https://github.com/abadiet/GarminServerLess/blob/main/GSL/device.py#L145). I think that Garmin sign apps in order to avoid MITM acttacks: by signing packages, no one can change it on the fly.
You should be able to see a RSA key in your GarminDevice.xml located at the root of your watch.

**Comment by daitj** [comment]
I was just testing update function in a test folder in my PC, which had same files from the device. When I tried to create `ExtData` directory, which was missing, apparently it cannot be created through MTP connection. 

README had `myDevice = Device("/dev/ttyACM0")` this, are you actually connecting to the device like this?

**Comment by abadiet** [comment]
No actually I never tried `myDevice = Device("/dev/ttyACM0")`. Like you are doing, I ran everything on a test folder with the same architecture as my device's one. Tbh, I though it would work through MTP but I may have wrong. Anyway, let's work first with local copies of the devices, and then we'll see
By the way, why do you need an `ExtData` directory? I don't have one too, was it requested by an update?

**Comment by daitj** [comment]
Yeah some of the update had it, haven't checked which one, but this is how they looked liked. It could of course be some secret folder that Garmin Express is suppose handle them differently than just copying them to the device. 

```
File             Size
006-D8168-13.tmp 7442321
006-D8448-25.tmp 3809005
006-D8448-26.tmp 5177405
006-D8448-27.tmp 6760129
006-D8448-28.tmp 8563929
006-D8944-20.tmp 1170742
006-D8944-21.tmp 1558347
006-D8944-22.tmp 1999530
006-D8944-23.tmp 2570053
006-D8945-20.tmp 1834538
006-D8945-21.tmp 2382097
006-D8945-22.tmp 3095569
006-D8945-23.tmp 4012686
006-D8947-20.tmp 13601
006-D8947-21.tmp 17552
006-D8947-22.tmp 22529
006-D8947-23.tmp 29289
006-D9035-01.tmp 13181
006-D9035-02.tmp 16676
006-D9035-03.tmp 20720
006-D9035-04.tmp 27831
```

**Comment by abadiet** [comment]
After a few search, it looks like it is a folder dedicated to .bin files such as specific fonts and updates, located under Garmin/ExtData.
Btw, a guy mentioned a Garmin software I never heard about on [this forum](https://forums.garmin.com/sports-fitness/sports-fitness/f/edge-explore/225456/two-files-in-folder-extdata-appeared-what-purpose-they-have): **[WebUpdater](https://www8.garmin.com/products/webupdater/howtoinstall.jsp)**. I will take a look later as it might be interesting to reverse engineer it too.

**Comment by daitj** [comment]
I think we can close this, apps started to work when I updated the watch to latest version from 15.02 to 19.05

Things that changed was the value in this tag:
```
<StoreKey><Modulus>
```
and VmVersion changed from `4.2.3` to
```
<VmVersion>5.0.0</VmVersion>
```
